[package]
name = "aoc_2022"
version = "0.1.0"
edition = "2021"
default-run = "aoc_2022"

[dependencies]
clap = { version = "4.0.8", features = ["derive"] }
colored = "2.0.0"
regex = "1.7.0"
reqwest = { version = "0.11.13", features = ["blocking"] }
html2md = "0.2.13"
